"""empty message

Revision ID: 88de4d31a7fe
Revises: 
Create Date: 2020-11-18 13:34:08.593533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88de4d31a7fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avg_salary', sa.Float(), nullable=False),
    sa.Column('count_employees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('department_info')
    op.drop_table('departments')
    # ### end Alembic commands ###
