"""empty message

Revision ID: e84736d978bd
Revises: 2f601a5e57ec
Create Date: 2020-11-21 13:19:09.529273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84736d978bd'
down_revision = '2f601a5e57ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('email', sa.String(length=200),
                                           nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'email')
    # ### end Alembic commands ###
