sudo: false

language: python
python:
    - "3.8"
services:
    - mysql
before_install:
    - sudo mysql -e "CREATE DATABASE testing_db; SHOW DATABASES; USE testing_db;"
    - echo "USE mysql;\nALTER USER 'root'@'localhost' IDENTIFIED BY 'root';\nFLUSH privileges;" | mysql -u root
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - python -m pylint --fail-under=9 --load-plugins pylint_flask_sqlalchemy --ignore=venv,migrations department-app/
    - coverage run --source=department-app/ -m unittest discover -s department-app/
after_script:
    - coveralls
