sudo: false

language: python
python:
    - "3.8"
install:
    - pip install pylint
    - pip install -r requirements.txt
script:
    - pylint --output-format=text department-app
    - coverage run --source=department-app/tests test
after_success:
    - coveralls
