sudo: false

language: python
python:
    - "3.8"
install:
    - pip install pylint
    - pip install pylint_flask_sqlalchemy
    - pip install -r requirements.txt
script:
    - coverage run -m unittest discover department-app/tests
    - coverage run -m pylint --load-plugins pylint_flask_sqlalchemy --ignore=venv,migrations department-app/
after_script:
    - coveralls
